### ISSUE TITLE
Can't download gawkextlib-csv

### ISSUE THREAD

**Issue by gtackett** [gavinestey/homebrew-gawkextlib#2] opened 2021-01-13 16:10 UTC
```
$ brew install gawkextlib-csv
==> Installing gawkextlib-csv from gavinestey/gawkextlib
==> Downloading https://homebrew.bintray.com/bottles/automake-1.16.3.mojave.bott
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/6e25193e573d0e1137632
######################################################################## 100.0%
==> Downloading https://downloads.sourceforge.net/project/gawkextlib/gawkextlib-
==> Downloading from https://netactuate.dl.sourceforge.net/project/gawkextlib/ga
######################################################################## 100.0%
==> Downloading https://downloads.sourceforge.net/code-snapshots/git/g/ga/gawkex

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "gawkextlib-csv"
Download failed: https://downloads.sourceforge.net/code-snapshots/git/g/ga/gawkextlib/code.git/gawkextlib-code-9ec2589edd164e18aba27cb854f22a0bca62763f.zip
```

**Comment by gavinestey** [comment] 2021-01-13 19:15
Duplicate of #1

**Closed as completed** 2021-01-13 19:15 UTC
